const aslideMenu=[
    {
        name:"data",
        title:"概要",
        authority:["admin","consumer"],
        icon:"el-icon-location",
        children:[{
            to:"/home/showData",
            name:"data",
            title:"今日概要",
            authority:["admin","consumer"],
        }]
    },
    {
        name:"banner",
        title:"banner管理",
        authority:["admin"],
        icon:"el-icon-menu",
        children:[{
            to:"/home/bannerlist",
            name:"banner",
            title:"banner列表",
            authority:["admin"],
        }]
    },{
        name:"shop",
        title:"shop管理",
        authority:["admin","consumer"],
        icon:"el-icon-document",
        children:[{
            to:"/home/shoplist",
            name:"shop",
            title:"商品列表",
            authority:["admin","consumer"], 
        },{
            to:"/home/shopadd",
            name:"shop",
            title:"商品添加",
            authority:["consumer","admin"],
        },{
            to:"/home/shoptype",
            name:"shop",
            title:"商品分类",
            authority:["admin"],
        }]
    }
]
export default aslideMenu